apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels:
    app: web
    tier: web
    project: roboshop
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: web
      tier: web
      project: roboshop
  template:
    metadata:
      labels:
        app: web
        tier: web
        project: roboshop
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
      containers:
      - name: web
        imagePullPolicy: Always
        image: kanalavinodkumar/web:{{ .Values.web.imageVersion }}
        resources:
          requests:
            cpu: "50m"
            memory: "68Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: web
    namespace: roboshop
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/tags: project=roboshop
        alb.ingress.kubernetes.io/group.name: vinodhub
spec:
  ingressClassName: alb
  rules:
  - host: "web.vinodhub.online"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80