apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels:
    app: web
    tier: web
    project: roboshop
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: web
      tier: web
      project: roboshop
  template:
    metadata:
      labels:
        app: web
        tier: web
        project: roboshop
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
      containers:
      - name: web
        imagePullPolicy: Always
        image: kanalavinodkumar/web:{{ .Values.web.imageVersion }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf