kind: Deployment
apiVersion: apps/v1
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    app: payment
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: payment
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        app: payment
        tier: app
    spec:
      containers:
        - name: payment
          image: kanalavinodkumar/payment:v1
---
kind: Service
apiVersion: v1
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    app: payment
    tier: app
spec:
  selector:
    # pod -labels
    project: roboshop
    app: payment
    tier: app
  ports:
  - name: payment-port
    protocol: TCP
    # service-port
    port: 8080
    # pod-port
    targetPort: 8080