kind: Deployment
apiVersion: apps/v1
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    app: user
    tier: app
spec:
  replicas: {{ .Values.user.replicaCount }}
  selector:
    matchLabels:
      project: roboshop
      app: user
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        app: user
        tier: app
    spec:
      containers:
        - name: user
          image: kanalavinodkumar/user:{{ .Values.user.imageVersion }}
          resources:
            requests:
              cpu: "50m"
              memory: "68Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"