kind: ConfigMap
apiVersion: v1
metadata:
  name: cart-config
data:
  REDIS_HOST: redis
  CATALOGUE_HOST: catalogue
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    app: cart
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: cart
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        app: cart
        tier: app
    spec:
      containers:
        - name: cart
          image: kanalavinodkumar/cart:v1
          envFrom:
          - configMapRef:
              name: cart-config
---
kind: Service
apiVersion: v1
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    app: cart
    tier: app
spec:
  selector:
    # pod -labels
    project: roboshop
    app: cart
    tier: app
  ports:
  - name: cart-port
    protocol: TCP
    # service-port
    port: 8080
    # pod-port
    targetPort: 8080