apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
data: 
  CART_ENDPOINT: "cart:8080"
  DB_HOST: mysql
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    app: shipping
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: shipping
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        app: shipping
        tier: app
    spec:
      containers:
        - name: shipping
          image: kanalavinodkumar/shipping:v1
          envFrom:
            - configMapRef:
              name: shipping-config
---
kind: Service
apiVersion: v1
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    app: shipping
    tier: app
spec:
  selector:
    # pod -labels
    project: roboshop
    app: shipping
    tier: app
  ports:
  - name: shipping-port
    protocol: TCP
    # service-port
    port: 8080
    # pod-port
    targetPort: 8080