apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq

  labels:
    project: roboshop
    app: rabbitmq
    tier: db
spec:
  selector:
    matchLabels:    # has to match .spec.template.metadata.labels
      project: roboshop
      app: rabbitmq
      tier: db
  serviceName: "rabbitmq"
  replicas: 1
  template:
    metadata:
      labels:   # has to match .spec.selector.matchLabels
        project: roboshop
        app: rabbitmq
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq

        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
  # this is PVC
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    app: rabbitmq
    tier: db
spec:
  selector:     # pod -labels
    project: roboshop
    app: rabbitmq
    tier: db
  ports:
  - name: rabbitmq-port
    protocol: TCP
    port: 5672      # service-port
    targetPort: 5672      # pod-port