kind: Deployment
apiVersion: apps/v1
metadata:
  name: ratings
  namespace: roboshop
  labels:
    project: roboshop
    app: ratings
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: ratings
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        app: ratings
        tier: app
    spec:
      containers:
        - name: ratings
          image: kanalavinodkumar/ratings:v1
---
kind: Service
apiVersion: v1
metadata:
  name: ratings
  namespace: roboshop
  labels:
    project: roboshop
    app: ratings
    tier: app
spec:
  selector:
    # pod -labels
    project: roboshop
    app: ratings
    tier: app
  ports:
  - name: ratings-port
    protocol: TCP
    # service-port
    port: 80
    # pod-port
    targetPort: 80