---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    app: mongodb
    tier: DB
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: mongodb
      tier: DB
  template:
    metadata:
      labels:
        project: roboshop
        app: mongodb
        tier: DB
    spec:
      containers:
        - name: mongodb
          image: kanalavinodkumar/mongodb:v1
---
kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    app: mongodb
    tier: DB
spec:
  selector:
    # pod -labels
    project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    # service-port
    port: 27017
    # pod-port
    targetPort: 27017