apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb

  labels:
    project: roboshop
    app: mongodb
    tier: db
spec:
  selector:
    matchLabels:    # has to match .spec.template.metadata.labels
      project: roboshop
      app: mongodb
      tier: db
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:   # has to match .spec.selector.matchLabels
        project: roboshop
        app: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: kanalavinodkumar/mongodb:v1

        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  # this is PVC
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    project: roboshop
    app: mongodb
    tier: db
spec:
  clusterIP: None #headless
  selector:   # you should provide pod labels here
    project: roboshop
    app: mongodb
    tier: db
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017   # service port
    targetPort: 27017   # container port