kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    app: mongodb
    tier: DB
spec:
  selector:
    # pod -labels
    project: roboshop
    app: mongodb
    tier: DB
  ports:
  - name: mongodb-port
    protocol: TCP
    # service-port
    port: 27017
    # pod-port
    targetPort: 27017
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: DB
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "mongodb"
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mongodb
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 27017
          name: db
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  # this is PVC
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-dynamic-sc"
      resources:
        requests:
          storage: 1Gi