apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    project: roboshop
    app: mysql
    tier: db
spec:
  selector:
    matchLabels:    # has to match .spec.template.metadata.labels
      project: roboshop
      app: mysql
      tier: db
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:   # has to match .spec.selector.matchLabels
        project: roboshop
        app: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: kanalavinodkumar/mysql:v1
        envFrom:
        - configMapRef:
            name: mysql-config
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  # this is PVC
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    tier: db
    project: roboshop
spec:
  clusterIP: None     #headless
  selector:   # you should provide pod labels here
    app: mysql
    tier: db
    project: roboshop
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306          # service port
    targetPort: 3306    # pod port

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: roboshop
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"   #keep in double quotes
  MYSQL_DATABASE: cities
  MYSQL_USER: shipping
  MYSQL_PASSWORD: secret
---