apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data: 
  MYSQL_ALLOW_EMPTY_PASSWORD: yes
  MYSQL_DATABASE: cities
  MYSQL_USER: shipping
  MYSQL_PASSWORD: secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    app: mysql
    tier: DB
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: mysql
      tier: DB
  template:
    metadata:
      labels:
        project: roboshop
        app: mysql
        tier: DB
    spec:
      containers:
        - name: mysql
          image: kanalavinodkumar/mysql:v1
          envFrom:
          - configMapRef:
              name: mysql-config
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    app: mysql
    tier: DB
spec:
  selector:
    # pod -labels
    project: roboshop
    app: mysql
    tier: DB
  ports:
  - name: mysql-port
    protocol: TCP
    # service-port
    port: 27017
    # pod-port
    targetPort: 27017