kind: Deployment
apiVersion: apps/v1
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    app: catalogue
    tier: app
spec:
  replicas: {{ .Values.catalogue.replicaCount }}
  selector:
    matchLabels:
      project: roboshop
      app: catalogue
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        app: catalogue
        tier: app
    spec:
      containers:
        - name: catalogue
          image: kanalavinodkumar/catalogue:{{ .Values.catalogue.imageVersion }}