apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: payment
    namespace: roboshop
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/tags: project=roboshop
        alb.ingress.kubernetes.io/group.name: vinodhub
spec:
  ingressClassName: alb
  rules:
  - host: "payment.vinodhub.online"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: payment
            port:
              number: 80