apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis

  labels:
    project: roboshop
    app: redis
    tier: db
spec:
  selector:
    matchLabels:    # has to match .spec.template.metadata.labels
      project: roboshop
      app: redis
      tier: db
  serviceName: "redis"
  replicas: 1
  template:
    metadata:
      labels:   # has to match .spec.selector.matchLabels
        project: roboshop
        app: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: redis

        volumeMounts:
        - name: redis
          mountPath: /data
  # this is PVC
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    app: redis
    tier: db
spec:
  clusterIP: None     #headless
  selector:   # pod labels
    project: roboshop
    app: redis
    tier: db
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379    # service-port
    targetPort: 6379    # pod-port